from setuptools import setup, find_packages

setup(
    name='damp11113',
    version='2022.11.14.8.14.3',
    license='MIT',
    author='damp11113',
    author_email='damp51252@gmail.com',
    packages=find_packages('src'),
    package_dir={'': 'src'},
    url='https://github.com/damp11113/damp11113-library',
    description='A Utils library and Easy to using.',
    install_requires=[
        "Pygments",
        "natsort",
        "psutil",
        "libscrc",
        "PyAudio",
        "python-vlc",
        "youtube_dl",
        "pafy",
        "pafy 2 @ git+https://github.com/damp11113/pafy2.git",
        "ffmpeg-python",
        "opencv-python",
        "tqdm",
        "numpy",
        "qrcode",
        "python-barcode",
        "Pillow",
        "yt-dlp",
        "pyzbar",
        "mcstatus",
        "requests",
        "mcrcon",
        "paho-mqtt",
        "pymata-aio",
        "key-generator",
        "gTTS",
        "playsound",
        "PyQt5"
    ]
)